@echo off
echo Adding changes...
git add .
echo Committing fix for 401 unauthorized errors...
git commit -m "Fix: Handle 401 Unauthorized errors by redirecting to login"
echo Pushing to origin main...
git push origin main

